# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install build dependencies for native modules
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy dependency manifests
COPY package.json bun.lock esbuild.js tsconfig.json ./
COPY src ./src
COPY schemas ./schemas
COPY resources ./resources
COPY snippets ./snippets
COPY esbuild.js .

# Install dependencies without running any prepare scripts
RUN npm install --ignore-scripts --legacy-peer-deps

# Build the extension and MCP server
RUN npm run compile

# Expose any needed ports (the server fetches http on localhost:50001 via remote DB service)
EXPOSE 50001

# Default command to run MCP server
CMD ["node", "dist/services/mcp/server.js"]
