name: Pre-release
on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: pre-release
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
            npm_config_arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            platform: linux
            arch: armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            platform: alpine
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64
            npm_config_arch: x64
          - os: macos-latest
            platform: darwin
            arch: arm64
            npm_config_arch: arm64
    runs-on: ${{ matrix.os }}
    if: github.ref == 'refs/heads/dev' || (startsWith(github.ref, 'refs/tags/') && github.ref_name == 'dev')
    steps:
      - name: Install macOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install python-setuptools
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          npm_config_arch: ${{ matrix.npm_config_arch }}
      - shell: pwsh
        run: echo "target=${{ matrix.platform }}-${{ matrix.arch }}" >> $env:GITHUB_ENV
      - run: npm run compile && npx vsce package --pre-release --target ${{ env.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.target }}
          path: '*.vsix'

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - uses: actions/checkout@v4
        # Ensure we can get latest tag futher below by including tags
        # More details at https://github.com/actions/checkout/issues/1471#issuecomment-1755639487
        with:
          fetch-depth: 0
          filter: tree:0
      - uses: actions/download-artifact@v4
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0) || { echo "No existing tags found. Please create a tag first."; exit 1; }
          gh release create $LATEST_TAG --generate-notes
          for file in **/*.vsix; do
            gh release upload $LATEST_TAG "$file"
          done
      - run: npx vsce publish --pre-release --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish to OpenVSX Registry
        run: |
          for file in **/*.vsix; do
            npx ovsx publish "$file" -p ${{ secrets.OPEN_VSX_DEVDB_TOKEN }}
          done
