name: Close inactive issues
on:
  schedule:
    - cron: "1 1 1,14 * *"

permissions:
  contents: read

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          any-of-labels: needs more info,awaiting response
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity and the 'awaiting response' tag persists. Please note that it will be auto-closed soon if there is still no response. Thank you."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
